services:
  api1:
    image: shobon03/rinha-backend-2026-go:latest
    security_opt:
      - seccomp=unconfined
    environment:
      - GOMAXPROCS=1
      - GOGC=100
      - SOCKET_PATH=/sockets/api1.sock
    volumes:
      - ./resources:/app/resources:ro
      - shared-socket:/sockets:rw
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 155MB
    networks:
      - rinha-network

  api2:
    image: shobon03/rinha-backend-2026-go:latest
    security_opt:
      - seccomp=unconfined
    environment:
      - GOMAXPROCS=1
      - GOGC=100
      - SOCKET_PATH=/sockets/api2.sock
    volumes:
      - ./resources:/app/resources:ro
      - shared-socket:/sockets:rw
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 155MB
    networks:
      - rinha-network

  haproxy:
    image: haproxy:latest
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - shared-socket:/sockets:rw
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 40MB
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge

volumes:
  shared-socket:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=16m,mode=1777
