services:
  api1:
    build: .
    image: shobon03/rinha-backend-2026-go:latest
    environment:
      - GOMAXPROCS=1
      - GOGC=100
      - SOCKET_PATH=/tmp/api1.sock
    volumes:
      - ./resources:/app/resources:ro
      - shared-socket:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 155MB
    networks:
      - rinha-network

  api2:
    build: .
    image: shobon03/rinha-backend-2026-go:latest
    environment:
      - GOMAXPROCS=1
      - GOGC=100
      - SOCKET_PATH=/tmp/api2.sock
    volumes:
      - ./resources:/app/resources:ro
      - shared-socket:/tmp
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: 155MB
    networks:
      - rinha-network

  haproxy:
    image: haproxy:latest
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - shared-socket:/tmp
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 40MB
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge

volumes:
  shared-socket:
